version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name last-work --s3-location s3://last-work-s3bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
